# Exemplo de pesquisa álbuns
GET http://localhost:8080/album
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6ImZjMGU2NDZmLTdkNjEtNDg3MS04NDE2LWJhMGZlMTBhZGNmNyIsImF1dGhvcml6ZWQiOnRydWUsImV4cCI6MTcyMjAyNzgwNSwidXNlcl9pZCI6MX0.ZVBgDI6pJ6ncFey0Z9pgdo_TKOldirud4aXP912U408

###

# Exemplo de Criação de álbum
POST http://localhost:8080/album
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6ImEwNWI5N2E3LTRmN2UtNDBlYy1hNDdjLWE0OGE3NTMzYzk3ZSIsImF1dGhvcml6ZWQiOnRydWUsImV4cCI6MTcyMjAyMTQ3OCwidXNlcl9pZCI6MX0.L4BcndEJRcmV6ymPvex_T2VJA0iYosUmAyHzR5HKzZ0

{
	"title": "Led Zeppelin IV",
	"artist": "Led Zeppelin",
	"price": 47.99
}

###

# Exemplo de Criação de álbum
POST http://localhost:8080/album
Content-Type: application/json

{
	"title": "Train of Thought",
	"artist": "Dream Theater",
	"price": 21.99
}

###

# Exemplo de Criação de álbum
POST http://localhost:8080/album
Content-Type: application/json

{
	"title": "Machine Head",
	"artist": "Deep Purple",
	"price": 39.99
}

###

# Exemplo de pesquisa álbum pelo ID
GET http://localhost:8080/album/ecbcb529-e6ce-4fee-b89f-bf62b3aa2273
Content-Type: application/json

###

# Exemplo de delete álbum pelo id
DELETE http://localhost:8080/album/11f778ce-921b-4518-8bc9-05057c641127
Content-Type: application/json

###

# Exemplo health
GET http://localhost:8080/health
Content-Type: application/json

{
  	"Username": "username",
	"Password": "password"
}


###

# Exemplo de criação de token
POST http://localhost:8080/login
Content-Type: application/json

{
  	"Username": "username",
	"Password": "password"
}


###
# Exemplo de todo
GET http://localhost:8080/health
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6ImEwNWI5N2E3LTRmN2UtNDBlYy1hNDdjLWE0OGE3NTMzYzk3ZSIsImF1dGhvcml6ZWQiOnRydWUsImV4cCI6MTcyMjAyMTQ3OCwidXNlcl9pZCI6MX0.L4BcndEJRcmV6ymPvex_T2VJA0iYosUmAyHzR5HKzZ0

{
  	"user_id": 1,
	"title": "teste title"
}

###

# Exemplo de logout
POST http://localhost:8080/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6ImEwNWI5N2E3LTRmN2UtNDBlYy1hNDdjLWE0OGE3NTMzYzk3ZSIsImF1dGhvcml6ZWQiOnRydWUsImV4cCI6MTcyMjAyMTQ3OCwidXNlcl9pZCI6MX0.L4BcndEJRcmV6ymPvex_T2VJA0iYosUmAyHzR5HKzZ0

###
# Exemplo de refresh token
# Neste caso, dev ser utilizado o access_token no header e passados os dois tokens 
# no body
POST http://localhost:8080/token/refresh
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6IjllNGZhOTRkLTNlMDgtNGVkMC1iZTUzLTQxOTQ0NDMxMTJlNCIsImF1dGhvcml6ZWQiOnRydWUsImV4cCI6MTcyMTczMTkyNiwidXNlcl9pZCI6MX0.zgW3HfsCbc9XGEwKyLb1KhElzUOQH0xsieZ2S_-L1AA

{
  "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6IjllNGZhOTRkLTNlMDgtNGVkMC1iZTUzLTQxOTQ0NDMxMTJlNCIsImF1dGhvcml6ZWQiOnRydWUsImV4cCI6MTcyMTczMTkyNiwidXNlcl9pZCI6MX0.zgW3HfsCbc9XGEwKyLb1KhElzUOQH0xsieZ2S_-L1AA",
  "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjIzMzU4MjYsInJlZnJlc2hfdXVpZCI6IjQxZDAwY2VmLTkxNmEtNDVlNC04ZDU3LThkODdmNmMzNGU1NyIsInVzZXJfaWQiOjF9.oJqLq9kCeVZ2bnWwi7oj_N3FtJDkBO-bHNgHjhjinBI"
}