# Exemplo de pesquisa álbuns
GET http://localhost:8080/album
Content-Type: application/json

###

# Exemplo de Criação de álbum
POST http://localhost:8080/album
Content-Type: application/json

{
	"title": "Blue Train",
	"artist": "John Coltrane",
	"price": 56.99
}

###

# Exemplo de Criação de álbum
POST http://localhost:8080/album
Content-Type: application/json

{
	"title": "Jeru",
	"artist": "Gerry Mulligan",
	"price": 17.99
}

###

# Exemplo de Criação de álbum
POST http://localhost:8080/album
Content-Type: application/json

{
	"title": "The Modern Sound of Betty Carter",
	"artist": "Betty Carter",
	"price": 49.99
}

###

# Exemplo de pesquisa álbum pelo ID
GET http://localhost:8080/album/a550b720-8c4b-4b22-860a-7417229a5332
Content-Type: application/json

###

# Exemplo de delete álbum pelo id
DELETE http://localhost:8080/albums/2
Content-Type: application/json

###

#
#
# Exemplo de criação de token
POST http://localhost:8080/login
Content-Type: application/json

{
  	"Username": "username",
	"Password": "password"
}

###



#
#
# Exemplo de todo
POST http://localhost:8080/todo
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6IjcwODFiZTllLTUzZTctNGQ0MS1iOWUzLTY5ZGVkZmE4MmZlMiIsImF1dGhvcml6ZWQiOnRydWUsImV4cCI6MTcyMDk3ODQ3MywidXNlcl9pZCI6MX0.TmxcYlNJxn2w-DnZctkgzhkjr5LF4f6e3w-RCXTxWeo

{
  	"user_id": 1,
	"title": "teste title"
}

###

# Exemplo de logout
POST http://localhost:8080/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6IjQ5YTY1NTM5LTY2ODQtNGI0MC1hOTkyLTlhNmY2NmE0NjcyNSIsImF1dGhvcml6ZWQiOnRydWUsImV4cCI6MTcyMDk3OTYzMiwidXNlcl9pZCI6MX0.f9L7q0e_Mz0d4IoZ4qg7uyEbvAgIFrSuXDI6JDSvCLs

###
# Exemplo de refresh token
# Neste caso, dev ser utilizado o access_token no header e passados os dois tokens 
# no body
POST http://localhost:8080/token/refresh
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6IjY0MDRhZjI5LTQwZDQtNGVlZC1iNTY4LThhYzU2YWNmZWZmNSIsImF1dGhvcml6ZWQiOnRydWUsImV4cCI6MTcyMDk4MDUyNSwidXNlcl9pZCI6MX0.DHVZuLFRAR7mwHty6LxxbcIfB6q2t-HSwCQlUITDnfc

{
  "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6IjY0MDRhZjI5LTQwZDQtNGVlZC1iNTY4LThhYzU2YWNmZWZmNSIsImF1dGhvcml6ZWQiOnRydWUsImV4cCI6MTcyMDk4MDUyNSwidXNlcl9pZCI6MX0.DHVZuLFRAR7mwHty6LxxbcIfB6q2t-HSwCQlUITDnfc",
  "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjE1ODQ0MjUsInJlZnJlc2hfdXVpZCI6ImQwOTgyZDI1LTI0MTUtNGI3MC05ZGZkLTUxMzJmMGYwZDY3MyIsInVzZXJfaWQiOjF9.k9ZkTwus6VYANA68PxrXPO7C1LQ4QQDzDsjHzIVEhrQ"
}