services:
  redis:
    container_name: redis
    image: redis
    command: redis-server --requirepass redis123
    ports:
      - "6379:6379"

  rate-limiter:
    container_name: rate-limiter
    build:
      context: .
    environment:
      MAX_REQUESTS_PER_SECOND: 5
      BLOCK_DURATION: 60
      MAX_REQUESTS_PER_SECOND_TOKEN: 10
      BLOCK_DURATION_TOKEN: 60
      REDIS_ADDRESS: "redis:6379"
      REDIS_PASSWORD: "redis123"
    ports:
      - "8080:8080"
    depends_on:
      - redis




